### ISSUE TITLE
hi，不知怎么把脚本放启动文件夹，但还是无法正常启动。

### ISSUE THREAD

**Issue by mgdreamingstar** [waldens/AutoHotkey-Script#1]
![snipaste20170322_003954](https://cloud.githubusercontent.com/assets/26304780/24158977/d77796d0-0e98-11e7-9691-a527e05a8a99.png)

1. 放启动文件夹
2. 添加启动项到注册表

都是上面图片里面的状况：可以在*任务管理器*看到这两项，但其实是没有启动的。所有快捷键都没用。
不知这种情况怎么解决。。。多谢。

**Comment by waldens** [comment]
任务管理器有进程吗？有进程就是启动了
双击托盘图标，可以看到脚本“最近执行的行”，有没触发快捷键？
注意是把脚本快捷方式放入启动文件夹，不能直接复制过去

**Comment by waldens** [comment]
[L521](https://github.com/waldens/AutoHotkey-Script/blob/dceb41d13b2f8eb308f5730bb963cb54f1ae23de/_MyScript/2.%20%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BF%AB%E6%8D%B7%E6%93%8D%E4%BD%9C.ahk#L521)到[L602](https://github.com/waldens/AutoHotkey-Script/blob/dceb41d13b2f8eb308f5730bb963cb54f1ae23de/_MyScript/2.%20%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BF%AB%E6%8D%B7%E6%93%8D%E4%BD%9C.ahk#L602) 是印象笔记相关的函数，可以直接拷贝到你的脚本里用，加上
```
#Include %A_LineFile%\..\..\Functions\WinClip\WinClipAPI.ahk
#Include %A_LineFile%\..\..\Functions\WinClip\WinClip.ahk
```
这两个库

**Comment by mgdreamingstar** [comment]
嗯，刚刚把代码合并到一起了。之前还没熟悉结构。重启看了下，启动项中是成功启动了，但是进程里面没有。是放的快捷方式。在所有用户的「启动」文件夹和自己的「启动」文件夹都放过快捷方式，但都不行。症状都一样…… @waldens

**Comment by waldens** [comment]
我的脚本设定的习惯，不一定适合你……把函数拷过去用更好一点……

**Comment by mgdreamingstar** [comment]
嗯，是把需要的部分合并了…

**Comment by mgdreamingstar** [comment]
谢谢，🙂
